Import('*')

sources = Split('''
    testLoader.cpp
    testSubmesh.cpp
    testTinyXml.cpp
    testVector.cpp
    testPhysique.cpp
''')

# Build the unit tests.

env = env.Copy(tools=[cal3d, boost_test, python])
env.Append(CPPPATH=['../../..',
                    '../../../avatarwindow'])
imvu_test_program(
    env,
    'test_cal3d${IMVU_LIBRARY_SUFFIX}',
    [env.Object('TestFrameworkMain', '#/Source/TestFramework/TestFrameworkMain.cpp')] + sources)
